import type { Flight } from "@/types/flight";

export const MOCK_OUTBOUND: Flight[] = [
  {
    id: "cx564-out",
    airline: "Cathay Pacific",
    flightNumber: "CX564",
    from: "HKG",
    to: "FUK",
    depart: "08:30",
    arrive: "13:10",
    durationMinutes: 280,
    stops: 0,
    stopLabel: "Non-stop",
    price: 2800,
    bagKg: 23,
  },
  {
    id: "uo821-out",
    airline: "HK Express",
    flightNumber: "UO821",
    from: "HKG",
    to: "FUK",
    depart: "09:15",
    arrive: "14:05",
    durationMinutes: 290,
    stops: 0,
    stopLabel: "Non-stop",
    price: 1650,
    bagKg: 0,
  },
  {
    id: "jl9613-out",
    airline: "Japan Airlines",
    flightNumber: "JL9613",
    from: "HKG",
    to: "FUK",
    depart: "10:00",
    arrive: "15:30",
    durationMinutes: 330,
    stops: 1,
    stopLabel: "1 stop (NRT)",
    price: 3200,
    bagKg: 23,
  },
];

export const MOCK_RETURN: Flight[] = [
  {
    id: "cx565-ret",
    airline: "Cathay Pacific",
    flightNumber: "CX565",
    from: "FUK",
    to: "HKG",
    depart: "19:30",
    arrive: "22:15",
    durationMinutes: 165,
    stops: 0,
    stopLabel: "Non-stop",
    price: 2900,
    bagKg: 23,
  },
  {
    id: "uo822-ret",
    airline: "HK Express",
    flightNumber: "UO822",
    from: "FUK",
    to: "HKG",
    depart: "20:10",
    arrive: "23:05",
    durationMinutes: 175,
    stops: 0,
    stopLabel: "Non-stop",
    price: 1750,
    bagKg: 0,
  },
  {
    id: "nh1862-ret",
    airline: "ANA",
    flightNumber: "NH1862",
    from: "FUK",
    to: "HKG",
    depart: "18:50",
    arrive: "22:40",
    durationMinutes: 230,
    stops: 1,
    stopLabel: "1 stop (HND)",
    price: 3400,
    bagKg: 23,
  },
];
