export interface AirportOption {
  code: string;
  name: string;
  city: string;
  aliases: string[];
}

export const AIRPORT_OPTIONS: AirportOption[] = [
  // Asia-Pacific - Japan
  {
    code: 'HND',
    name: 'Tokyo Haneda',
    city: 'Tokyo',
    aliases: ['tokyo', 'haneda', '東京', '羽田', '東京羽田', 'japan', '日本'],
  },
  {
    code: 'NRT',
    name: 'Tokyo Narita',
    city: 'Tokyo',
    aliases: ['tokyo', 'narita', '東京', '成田', '東京成田', 'japan', '日本'],
  },
  {
    code: 'KIX',
    name: 'Kansai International',
    city: 'Osaka',
    aliases: ['osaka', 'kansai', '大阪', '關西', '关西', 'japan', '日本'],
  },
  {
    code: 'ITM',
    name: 'Osaka Itami',
    city: 'Osaka',
    aliases: ['osaka', 'itami', '大阪', '伊丹', 'japan', '日本'],
  },
  {
    code: 'NGO',
    name: 'Chubu Centrair',
    city: 'Nagoya',
    aliases: ['nagoya', 'chubu', '名古屋', '中部', 'japan', '日本'],
  },
  {
    code: 'CTS',
    name: 'New Chitose',
    city: 'Sapporo',
    aliases: [
      'sapporo',
      'chitose',
      '札幌',
      '新千歲',
      '新千岁',
      'japan',
      '日本',
    ],
  },
  {
    code: 'FUK',
    name: 'Fukuoka Airport',
    city: 'Fukuoka',
    aliases: ['fukuoka', '福岡', '福冈', '福岡機場', 'japan', '日本'],
  },
  {
    code: 'OKA',
    name: 'Naha Airport',
    city: 'Okinawa',
    aliases: ['naha', 'okinawa', '那霸', '沖繩', '沖绳', 'japan', '日本'],
  },
  {
    code: 'KOB',
    name: 'Kobe Airport',
    city: 'Kobe',
    aliases: ['kobe', '神戶', '神户', 'japan', '日本'],
  },
  {
    code: 'SDJ',
    name: 'Sendai Airport',
    city: 'Sendai',
    aliases: ['sendai', '仙台', 'japan', '日本'],
  },
  {
    code: 'HIJ',
    name: 'Hiroshima Airport',
    city: 'Hiroshima',
    aliases: ['hiroshima', '廣島', '广岛', 'japan', '日本'],
  },
  {
    code: 'MYJ',
    name: 'Miyazaki Airport',
    city: 'Miyazaki',
    aliases: ['miyazaki', '宮崎', '宫崎', 'japan', '日本'],
  },

  // Asia-Pacific - China & Hong Kong & Macau
  {
    code: 'HKG',
    name: 'Hong Kong International',
    city: 'Hong Kong',
    aliases: [
      'hong kong',
      'hk',
      '香港',
      '香港機場',
      '香港机场',
      '赤鱲角',
      '赤腊角',
      'china',
      '中国',
    ],
  },
  {
    code: 'PVG',
    name: 'Shanghai Pudong',
    city: 'Shanghai',
    aliases: ['shanghai', 'pudong', '上海', '浦東', '浦东', 'china', '中国'],
  },
  {
    code: 'SHA',
    name: 'Shanghai Hongqiao',
    city: 'Shanghai',
    aliases: ['shanghai', 'hongqiao', '上海', '虹橋', '虹桥', 'china', '中国'],
  },
  {
    code: 'PEK',
    name: 'Beijing Capital',
    city: 'Beijing',
    aliases: ['beijing', '北京', '首都', '北京首都', 'china', '中国'],
  },
  {
    code: 'PKX',
    name: 'Beijing Daxing',
    city: 'Beijing',
    aliases: ['beijing', 'daxing', '北京', '大興', '大兴', 'china', '中国'],
  },
  {
    code: 'CAN',
    name: 'Guangzhou Baiyun',
    city: 'Guangzhou',
    aliases: [
      'guangzhou',
      'canton',
      '廣州',
      '广州',
      '白雲',
      '白云',
      'china',
      '中国',
    ],
  },
  {
    code: 'SZX',
    name: "Shenzhen Bao'an",
    city: 'Shenzhen',
    aliases: ['shenzhen', '深圳', '寶安', '宝安', 'china', '中国'],
  },
  {
    code: 'MFM',
    name: 'Macau International',
    city: 'Macau',
    aliases: ['macau', 'macao', '澳門', '澳门', 'china', '中国'],
  },

  // Asia-Pacific - Taiwan
  {
    code: 'TPE',
    name: 'Taiwan Taoyuan',
    city: 'Taipei',
    aliases: [
      'taipei',
      'taoyuan',
      '台北',
      '桃園',
      '桃园',
      '台灣',
      '台湾',
      'taiwan',
    ],
  },
  {
    code: 'TSA',
    name: 'Taipei Songshan',
    city: 'Taipei',
    aliases: ['taipei', 'songshan', '台北', '松山', 'taiwan'],
  },
  {
    code: 'KHH',
    name: 'Kaohsiung International',
    city: 'Kaohsiung',
    aliases: ['kaohsiung', '高雄', 'taiwan'],
  },

  // Asia-Pacific - South Korea
  {
    code: 'ICN',
    name: 'Seoul Incheon',
    city: 'Seoul',
    aliases: [
      'seoul',
      'incheon',
      '首爾',
      '首尔',
      '仁川',
      '韓國',
      '韩国',
      'south korea',
      'korea',
    ],
  },
  {
    code: 'GMP',
    name: 'Seoul Gimpo',
    city: 'Seoul',
    aliases: ['seoul', 'gimpo', '首爾', '首尔', '金浦', 'south korea', 'korea'],
  },
  {
    code: 'PUS',
    name: 'Gimhae International',
    city: 'Busan',
    aliases: ['busan', 'pusan', '釜山', '金海', 'south korea', 'korea'],
  },
  {
    code: 'CJU',
    name: 'Jeju International',
    city: 'Jeju',
    aliases: ['jeju', '濟州', '济州', '제주', 'south korea', 'korea'],
  },

  // Asia-Pacific - Southeast Asia
  {
    code: 'SIN',
    name: 'Singapore Changi',
    city: 'Singapore',
    aliases: ['singapore', 'changi', '新加坡', '樟宜'],
  },
  {
    code: 'BKK',
    name: 'Bangkok Suvarnabhumi',
    city: 'Bangkok',
    aliases: [
      'bangkok',
      'suvarnabhumi',
      '曼谷',
      '素萬那普',
      '素万那普',
      'thailand',
      '泰國',
      '泰国',
    ],
  },
  {
    code: 'DMK',
    name: 'Bangkok Don Mueang',
    city: 'Bangkok',
    aliases: [
      'bangkok',
      'don mueang',
      'don muang',
      '曼谷',
      '廊曼',
      'thailand',
      '泰國',
      '泰国',
    ],
  },
  {
    code: 'HKT',
    name: 'Phuket International',
    city: 'Phuket',
    aliases: ['phuket', '普吉', '普吉島', '普吉岛', 'thailand', '泰國', '泰国'],
  },
  {
    code: 'CNX',
    name: 'Chiang Mai International',
    city: 'Chiang Mai',
    aliases: ['chiang mai', '清邁', '清迈', 'thailand', '泰國', '泰国'],
  },
  {
    code: 'KUL',
    name: 'Kuala Lumpur International',
    city: 'Kuala Lumpur',
    aliases: [
      'kuala lumpur',
      'klia',
      '吉隆坡',
      'malaysia',
      '馬來西亞',
      '马来西亚',
    ],
  },
  {
    code: 'PEN',
    name: 'Penang International',
    city: 'Penang',
    aliases: ['penang', '檳城', '槟城', 'malaysia', '馬來西亞', '马来西亚'],
  },
  {
    code: 'BKI',
    name: 'Kota Kinabalu International',
    city: 'Kota Kinabalu',
    aliases: [
      'kota kinabalu',
      'kk',
      '亞庇',
      '亚庇',
      'malaysia',
      '馬來西亞',
      '马来西亚',
    ],
  },
  {
    code: 'MNL',
    name: 'Manila Ninoy Aquino',
    city: 'Manila',
    aliases: ['manila', '馬尼拉', '马尼拉', 'philippines', '菲律賓', '菲律宾'],
  },
  {
    code: 'CEB',
    name: 'Mactan-Cebu International',
    city: 'Cebu',
    aliases: ['cebu', '宿霧', '宿雾', 'philippines', '菲律賓', '菲律宾'],
  },
  {
    code: 'SGN',
    name: 'Ho Chi Minh City Tan Son Nhat',
    city: 'Ho Chi Minh City',
    aliases: [
      'ho chi minh',
      'saigon',
      '胡志明',
      '西貢',
      '西贡',
      'vietnam',
      '越南',
    ],
  },
  {
    code: 'HAN',
    name: 'Hanoi Noi Bai',
    city: 'Hanoi',
    aliases: ['hanoi', '河內', '河内', 'vietnam', '越南'],
  },
  {
    code: 'DAD',
    name: 'Da Nang International',
    city: 'Da Nang',
    aliases: ['da nang', 'danang', '峴港', '岘港', 'vietnam', '越南'],
  },
  {
    code: 'DPS',
    name: 'Ngurah Rai International',
    city: 'Bali',
    aliases: [
      'bali',
      'denpasar',
      '峇里',
      '巴厘',
      '巴厘島',
      '巴厘岛',
      'indonesia',
      '印度尼西亞',
      '印度尼西亚',
    ],
  },
  {
    code: 'CGK',
    name: 'Jakarta Soekarno-Hatta',
    city: 'Jakarta',
    aliases: [
      'jakarta',
      '雅加達',
      '雅加达',
      'indonesia',
      '印度尼西亞',
      '印度尼西亚',
    ],
  },

  // South Asia
  {
    code: 'DEL',
    name: 'Indira Gandhi International',
    city: 'New Delhi',
    aliases: ['new delhi', 'delhi', '新德里', '德里', 'india', '印度'],
  },
  {
    code: 'BOM',
    name: 'Bombay Chhatrapati Shivaji',
    city: 'Mumbai',
    aliases: ['mumbai', 'bombay', '孟買', '孟买', 'india', '印度'],
  },

  // Middle East
  {
    code: 'DXB',
    name: 'Dubai International',
    city: 'Dubai',
    aliases: [
      'dubai',
      '杜拜',
      '迪拜',
      'uae',
      'united arab emirates',
      '阿聯酋',
      '阿联酋',
    ],
  },
  {
    code: 'AUH',
    name: 'Abu Dhabi International',
    city: 'Abu Dhabi',
    aliases: [
      'abu dhabi',
      '阿聯酋',
      '阿联酋',
      '阿布扎比',
      'uae',
      'united arab emirates',
    ],
  },
  {
    code: 'DOH',
    name: 'Hamad International',
    city: 'Doha',
    aliases: ['doha', '多哈', 'qatar', '卡塔爾', '卡塔尔'],
  },
  {
    code: 'RUH',
    name: 'King Fahd International',
    city: 'Riyadh',
    aliases: [
      'riyadh',
      '沙烏地',
      '沙乌地',
      '利雅得',
      'saudi arabia',
      '沙烏地阿拉伯',
      '沙乌地阿拉伯',
    ],
  },

  // Oceania - Australia & New Zealand
  {
    code: 'SYD',
    name: 'Sydney Kingsford Smith',
    city: 'Sydney',
    aliases: ['sydney', '悉尼', '雪梨', 'australia', '澳洲', '澳大利亚'],
  },
  {
    code: 'MEL',
    name: 'Melbourne Airport',
    city: 'Melbourne',
    aliases: ['melbourne', '墨爾本', '墨尔本', 'australia', '澳洲', '澳大利亚'],
  },
  {
    code: 'BNE',
    name: 'Brisbane Airport',
    city: 'Brisbane',
    aliases: ['brisbane', '布里斯班', 'australia', '澳洲', '澳大利亚'],
  },
  {
    code: 'PER',
    name: 'Perth Airport',
    city: 'Perth',
    aliases: ['perth', '珀斯', 'australia', '澳洲', '澳大利亚'],
  },
  {
    code: 'AKL',
    name: 'Auckland Airport',
    city: 'Auckland',
    aliases: [
      'auckland',
      '奧克蘭',
      '奥克兰',
      'new zealand',
      '紐西蘭',
      '纽西兰',
    ],
  },

  // Europe - UK & Ireland
  {
    code: 'LHR',
    name: 'London Heathrow',
    city: 'London',
    aliases: [
      'london',
      'heathrow',
      '倫敦',
      '伦敦',
      '希斯路',
      'uk',
      'united kingdom',
      '英國',
      '英国',
    ],
  },
  {
    code: 'LCY',
    name: 'London City',
    city: 'London',
    aliases: [
      'london',
      'city',
      '倫敦',
      '伦敦',
      '城市',
      'uk',
      'united kingdom',
      '英國',
      '英国',
    ],
  },

  // Europe - Continental
  {
    code: 'CDG',
    name: 'Paris Charles de Gaulle',
    city: 'Paris',
    aliases: [
      'paris',
      'charles de gaulle',
      '巴黎',
      '戴高樂',
      '戴高乐',
      'france',
      '法國',
      '法国',
    ],
  },
  {
    code: 'FRA',
    name: 'Frankfurt Airport',
    city: 'Frankfurt',
    aliases: ['frankfurt', '法蘭克福', '法兰克福', 'germany', '德國', '德国'],
  },
  {
    code: 'AMS',
    name: 'Amsterdam Schiphol',
    city: 'Amsterdam',
    aliases: [
      'amsterdam',
      'schiphol',
      '阿姆斯特丹',
      '史基浦',
      'netherlands',
      '荷蘭',
      '荷兰',
    ],
  },
  {
    code: 'BER',
    name: 'Berlin Brandenburg',
    city: 'Berlin',
    aliases: ['berlin', '柏林', 'germany', '德國', '德国'],
  },
  {
    code: 'VIE',
    name: 'Vienna International',
    city: 'Vienna',
    aliases: ['vienna', '維也納', '维也纳', 'austria', '奧地利', '奥地利'],
  },
  {
    code: 'ZRH',
    name: 'Zurich Airport',
    city: 'Zurich',
    aliases: ['zurich', '蘇黎世', '苏黎世', 'switzerland', '瑞士'],
  },
  {
    code: 'FCO',
    name: 'Leonardo da Vinci',
    city: 'Rome',
    aliases: ['rome', '羅馬', '罗马', '達文西', 'italy', '義大利', '意大利'],
  },
  {
    code: 'MAD',
    name: 'Adolfo Suárez',
    city: 'Madrid',
    aliases: ['madrid', '馬德里', '马德里', 'spain', '西班牙'],
  },
  {
    code: 'BCN',
    name: 'Josep Tarradellas',
    city: 'Barcelona',
    aliases: ['barcelona', '巴塞隆拿', '巴塞罗那', 'spain', '西班牙'],
  },
  {
    code: 'MXP',
    name: 'Malpensa',
    city: 'Milan',
    aliases: ['milan', '米蘭', '米兰', '馬爾彭薩', 'italy', '義大利', '意大利'],
  },
  {
    code: 'IST',
    name: 'Istanbul Airport',
    city: 'Istanbul',
    aliases: [
      'istanbul',
      '伊斯坦堡',
      '伊斯坦布爾',
      '伊斯坦布尔',
      'turkey',
      '土耳其',
    ],
  },

  // Europe - Nordic
  {
    code: 'OSL',
    name: 'Oslo Gardermoen',
    city: 'Oslo',
    aliases: ['oslo', '奧斯陸', '奥斯陆', '挪威', 'norway'],
  },
  {
    code: 'BGO',
    name: 'Bergen Airport',
    city: 'Bergen',
    aliases: ['bergen', '卑爾根', '卑尔根', '挪威', 'norway'],
  },
  {
    code: 'SVG',
    name: 'Stavanger Sola',
    city: 'Stavanger',
    aliases: ['stavanger', '史塔范格', '斯塔万格', 'norway'],
  },
  {
    code: 'TRD',
    name: 'Trondheim Vaernes',
    city: 'Trondheim',
    aliases: ['trondheim', '特隆赫姆', '特伦赫姆', 'norway'],
  },

  // Europe - Nordic - Finland
  {
    code: 'HEL',
    name: 'Helsinki-Vantaa',
    city: 'Helsinki',
    aliases: [
      'helsinki',
      '赫爾辛基',
      '赫尔辛基',
      '萬塔',
      '万塔',
      'finland',
      '芬蘭',
      '芬兰',
    ],
  },
  {
    code: 'TMP',
    name: 'Tampere-Pirkkala',
    city: 'Tampere',
    aliases: [
      'tampere',
      '坦佩雷',
      '皮爾卡拉',
      '皮尔卡拉',
      'finland',
      '芬蘭',
      '芬兰',
    ],
  },
  {
    code: 'OUL',
    name: 'Oulu Airport',
    city: 'Oulu',
    aliases: ['oulu', '烏盧', '乌卢', 'finland', '芬蘭', '芬兰'],
  },
  {
    code: 'TKU',
    name: 'Turku Airport',
    city: 'Turku',
    aliases: ['turku', '圖爾庫', '图尔库', 'finland', '芬蘭', '芬兰'],
  },

  // North America - US East
  {
    code: 'JFK',
    name: 'John F. Kennedy International',
    city: 'New York',
    aliases: [
      'new york',
      'nyc',
      '紐約',
      '纽约',
      '肯尼迪',
      'usa',
      'united states',
      'america',
      '美國',
      '美国',
    ],
  },
  {
    code: 'ORD',
    name: "Chicago O'Hare",
    city: 'Chicago',
    aliases: [
      'chicago',
      '芝加哥',
      '歐海',
      'usa',
      'united states',
      'america',
      '美國',
      '美国',
    ],
  },
  {
    code: 'ATL',
    name: 'Hartsfield-Jackson',
    city: 'Atlanta',
    aliases: [
      'atlanta',
      '亞特蘭大',
      '亚特兰大',
      'usa',
      'united states',
      'america',
      '美國',
      '美国',
    ],
  },
  {
    code: 'MIA',
    name: 'Miami International',
    city: 'Miami',
    aliases: [
      'miami',
      '邁阿密',
      '迈阿密',
      'usa',
      'united states',
      'america',
      '美國',
      '美国',
    ],
  },
  {
    code: 'BOS',
    name: 'Boston Logan',
    city: 'Boston',
    aliases: [
      'boston',
      '波士頓',
      '波士顿',
      'usa',
      'united states',
      'america',
      '美國',
      '美国',
    ],
  },
  {
    code: 'PHI',
    name: 'Philadelphia International',
    city: 'Philadelphia',
    aliases: [
      'philadelphia',
      '費城',
      '费城',
      'usa',
      'united states',
      'america',
      '美國',
      '美国',
    ],
  },

  // North America - US Central & South
  {
    code: 'DFW',
    name: 'Dallas/Fort Worth',
    city: 'Dallas',
    aliases: [
      'dallas',
      'fort worth',
      '達拉斯',
      '达拉斯',
      'usa',
      'united states',
      'america',
      '美國',
      '美国',
    ],
  },
  {
    code: 'DEN',
    name: 'Denver International',
    city: 'Denver',
    aliases: [
      'denver',
      '丹佛',
      'usa',
      'united states',
      'america',
      '美國',
      '美国',
    ],
  },

  // North America - US West
  {
    code: 'LAX',
    name: 'Los Angeles International',
    city: 'Los Angeles',
    aliases: [
      'los angeles',
      'la',
      '洛杉磯',
      '洛杉矶',
      'usa',
      'united states',
      'america',
      '美國',
      '美国',
    ],
  },
  {
    code: 'SFO',
    name: 'San Francisco International',
    city: 'San Francisco',
    aliases: [
      'san francisco',
      '三藩市',
      '舊金山',
      '旧金山',
      'usa',
      'united states',
      'america',
      '美國',
      '美国',
    ],
  },
  {
    code: 'SEA',
    name: 'Seattle-Tacoma International',
    city: 'Seattle',
    aliases: [
      'seattle',
      '西雅圖',
      '西雅图',
      'usa',
      'united states',
      'america',
      '美國',
      '美国',
    ],
  },

  // North America - Canada
  {
    code: 'YVR',
    name: 'Vancouver International',
    city: 'Vancouver',
    aliases: ['vancouver', '溫哥華', '温哥华', 'canada', '加拿大'],
  },
];
